import { PrismaClient, Role, OrderStatus } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database with full demo data...');

  // 1. Clean up existing data (optional but recommended for clean seed)
  // We'll use upsert instead to avoid breaking existing relations if any

  // 2. Categories from mockData.js
  const categoryNames = ["Shirts", "Trousers", "Jackets", "Formals", "Casuals", "Accessories"];
  const categoryRecords = {};

  for (const name of categoryNames) {
    const slug = name.toLowerCase().replace(/ /g, '-');
    const category = await prisma.category.upsert({
      where: { slug },
      update: {},
      create: { 
        name, 
        slug, 
        image: `https://placehold.co/400x400/0A1628/gold?text=${name}` 
      }
    });
    categoryRecords[name] = category;
  }

  // 3. Admin user
  const adminPassword = await bcrypt.hash('Admin@123', 10);
  await prisma.user.upsert({
    where: { email: 'admin@mensshop.com' },
    update: {},
    create: { 
      email: 'admin@mensshop.com', 
      password: adminPassword, 
      name: 'Admin User', 
      role: Role.ADMIN 
    },
  });

  // 4. Products from mockData.js
  const products = [
    { id: "v1", name: "Classic Navy Oxford Shirt", brand: "M all", category: "Shirts", price: 1899, originalPrice: 2499, discountPercent: 24, sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Navy", "White", "Light Blue"], fabric: "100% Premium Cotton", rating: 4.8, reviewCount: 124, images: ["https://placehold.co/600x800/0A1628/white?text=Navy+Oxford", "https://placehold.co/600x800/0A1628/gold?text=Detail+View"], description: "A timeless classic for the modern gentleman. Crafted from premium long-staple cotton for ultimate comfort and durability.", careInstructions: "Machine wash cold. Tumble dry low. Warm iron if needed.", inStock: true, isTrending: true },
    { id: "v2", name: "Charcoal Slim Fit Chinos", brand: "M all", category: "Trousers", price: 2299, originalPrice: 2299, discountPercent: 0, sizes: ["30", "32", "34", "36"], colors: ["Charcoal", "Beige", "Black"], fabric: "Stretch Cotton Twill", rating: 4.6, reviewCount: 89, images: ["https://placehold.co/600x800/2D2D2D/white?text=Charcoal+Chinos", "https://placehold.co/600x800/2D2D2D/gold?text=Detail+View"], description: "Versatile chinos that transition perfectly from office to evening. Features a modern slim silhouette.", careInstructions: "Wash with similar colors inside out.", inStock: true, isTrending: true },
    { id: "v3", name: "Urban Leather Biker Jacket", brand: "M all", category: "Jackets", price: 5499, originalPrice: 7999, discountPercent: 31, sizes: ["M", "L", "XL"], colors: ["Black", "Deep Brown"], fabric: "Genuine Leather", rating: 4.9, reviewCount: 56, images: ["https://placehold.co/600x800/111111/white?text=Leather+Jacket", "https://placehold.co/600x800/111111/gold?text=Biker+Detail"], description: "Make a statement with our signature leather biker jacket. Hand-finished for a vintage aesthetic.", careInstructions: "Professional leather clean only.", inStock: true, isTrending: false },
    { id: "v4", name: "Golden Silk Tie", brand: "M all", category: "Accessories", price: 999, originalPrice: 1499, discountPercent: 33, sizes: ["One Size"], colors: ["Gold", "Navy"], fabric: "100% Pure Silk", rating: 4.7, reviewCount: 32, images: ["https://placehold.co/600x800/C9A84C/white?text=Silk+Tie", "https://placehold.co/600x800/C9A84C/navy?text=Tie+Close-up"], description: "Add a touch of regality to your formal attire with this hand-stitched silk tie.", careInstructions: "Dry clean only.", inStock: true, isTrending: false },
    { id: "v5", name: "Midnight Suede Loafers", brand: "M all", category: "Casuals", price: 3499, originalPrice: 4500, discountPercent: 22, sizes: ["8", "9", "10", "11"], colors: ["Midnight Blue", "Tobacco"], fabric: "Italian Suede", rating: 4.5, reviewCount: 45, images: ["https://placehold.co/600x800/0A1628/white?text=Suede+Loafers", "https://placehold.co/600x800/0A1628/gold?text=Loafer+Texture"], description: "Unmatched comfort meet classic style. These loafers are a staple for any casual wardrobe.", careInstructions: "Use a brush for suede after wear.", inStock: true, isTrending: true },
    { id: "v6", name: "Executive Wool Blazer", brand: "M all", category: "Formals", price: 6999, originalPrice: 8999, discountPercent: 22, sizes: ["38", "40", "42", "44"], colors: ["Grey Melange", "Navy"], fabric: "100% Merino Wool", rating: 4.9, reviewCount: 28, images: ["https://placehold.co/600x800/2D2D2D/white?text=Wool+Blazer", "https://placehold.co/600x800/2D2D2D/gold?text=Blazer+Fit"], description: "Command the room in this precision-tailored merino wool blazer.", careInstructions: "Dry clean only.", inStock: true, isTrending: true },
    { id: "v7", name: "Essential White T-Shirt", brand: "M all", category: "Casuals", price: 799, originalPrice: 999, discountPercent: 20, sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["White", "Black", "Navy"], fabric: "Organic Heavyweight Cotton", rating: 4.8, reviewCount: 340, images: ["https://placehold.co/600x800/F5F5F0/0A1628?text=White+Tee", "https://placehold.co/600x800/F5F5F0/gold?text=Tee+Texture"], description: "The perfect heavyweight tee for everyday layering or standalone wear.", careInstructions: "Machine wash cold, tumble dry low.", inStock: true, isTrending: false },
    { id: "v8", name: "Dark Wash Selvedge Jeans", brand: "M all", category: "Trousers", price: 3899, originalPrice: 4999, discountPercent: 22, sizes: ["30", "32", "34", "36"], colors: ["Indigo"], fabric: "14oz Selvedge Denim", rating: 4.7, reviewCount: 78, images: ["https://placehold.co/600x800/0A1628/white?text=Selvedge+Jeans", "https://placehold.co/600x800/0A1628/gold?text=Denim+Detail"], description: "Durable, high-quality denim that ages beautifully with time. A true wardrobe investment.", careInstructions: "Wash inside out. Avoid washing frequently to maintain color.", inStock: true, isTrending: false },
    { id: "v9", name: "Quilted Winter Vest", brand: "M all", category: "Jackets", price: 2899, originalPrice: 3499, discountPercent: 17, sizes: ["S", "M", "L", "XL"], colors: ["Olive", "Navy"], fabric: "Recycled Polyester", rating: 4.6, reviewCount: 42, images: ["https://placehold.co/600x800/3A5F0B/white?text=Quilted+Vest", "https://placehold.co/600x800/3A5F0B/gold?text=Vest+Back"], description: "Lightweight yet warm quilted vest, perfect for transitional weather.", careInstructions: "Machine wash cold.", inStock: true, isTrending: false },
    { id: "v10", name: "Premium Leather Belt", brand: "M all", category: "Accessories", price: 1299, originalPrice: 1599, discountPercent: 18, sizes: ["32", "34", "36", "38"], colors: ["Tan", "Black"], fabric: "Full Grain Leather", rating: 4.7, reviewCount: 56, images: ["https://placehold.co/600x800/8B4513/white?text=Leather+Belt", "https://placehold.co/600x800/8B4513/gold?text=Buckle+Detail"], description: "Hand-finished full grain leather belt with a solid brass buckle.", careInstructions: "Wipe with a damp cloth.", inStock: true, isTrending: false },
    { id: "v11", name: "Minimalist Linen Shirt", brand: "M all", category: "Shirts", price: 2199, originalPrice: 2899, discountPercent: 24, sizes: ["S", "M", "L", "XL"], colors: ["Sand", "Sky Blue"], fabric: "Pure European Linen", rating: 4.8, reviewCount: 88, images: ["https://placehold.co/600x800/E3DAC9/0A1628?text=Linen+Shirt", "https://placehold.co/600x800/E3DAC9/gold?text=Linen+Texture"], description: "The ultimate summer shirt. Breathable, crisp, and effortlessly stylish.", careInstructions: "Wash with cool water. Hang dry.", inStock: true, isTrending: true },
    { id: "v12", name: "Tailored Dress Trousers", brand: "M all", category: "Formals", price: 3299, originalPrice: 3999, discountPercent: 17, sizes: ["30", "32", "34", "36", "38"], colors: ["Navy", "Charcoal"], fabric: "Wool Blend", rating: 4.9, reviewCount: 35, images: ["https://placehold.co/600x800/0A1628/white?text=Dress+Trousers", "https://placehold.co/600x800/0A1628/gold?text=Fit+Detail"], description: "Sharp and sophisticated. These trousers are the foundation of any power suit.", careInstructions: "Dry clean recommended.", inStock: true, isTrending: false },
    { id: "v13", name: "Heavyweight Denim Shirt", brand: "M all", category: "Shirts", price: 2499, originalPrice: 3200, discountPercent: 22, sizes: ["S", "M", "L", "XL"], colors: ["Indigo", "Light Wash"], fabric: "12oz Premium Denim", rating: 4.7, reviewCount: 45, images: ["https://placehold.co/600x800/0A1628/white?text=Denim+Shirt", "https://placehold.co/600x800/0A1628/gold?text=Denim+Detail"], description: "A rugged yet refined denim shirt built for layering or wearing on its own.", careInstructions: "Wash inside out with cold water.", inStock: true, isTrending: false },
    { id: "v14", name: "Grandad Collar Linen Shirt", brand: "M all", category: "Shirts", price: 2199, originalPrice: 2199, discountPercent: 0, sizes: ["S", "M", "L", "XL"], colors: ["White", "Sand", "Olive"], fabric: "100% European Linen", rating: 4.8, reviewCount: 32, images: ["https://placehold.co/600x800/F5F5F0/0A1628?text=Grandad+Shirt", "https://placehold.co/600x800/F5F5F0/gold?text=Collar+Detail"], description: "Sophisticated collarless design in breathable linen for a relaxed summer aesthetic.", careInstructions: "Hand wash or gentle cycle.", inStock: true, isTrending: true },
    { id: "v15", name: "Midnight Check Flannel", brand: "M all", category: "Shirts", price: 1699, originalPrice: 2200, discountPercent: 23, sizes: ["M", "L", "XL", "XXL"], colors: ["Navy/Red", "Grey/Black"], fabric: "Brushed Cotton Flannel", rating: 4.6, reviewCount: 78, images: ["https://placehold.co/600x800/2D2D2D/white?text=Flannel+Shirt", "https://placehold.co/600x800/2D2D2D/gold?text=Check+Detail"], description: "Ultra-soft brushed flannel in a classic checked pattern. Perfect for cooler days.", careInstructions: "Machine wash cold. Do not bleach.", inStock: true, isTrending: false },
    { id: "v16", name: "Printed Tropical Summer Shirt", brand: "M all", category: "Shirts", price: 1499, originalPrice: 1999, discountPercent: 25, sizes: ["S", "M", "L"], colors: ["Navy Print", "Teal Print"], fabric: "Rayon Viscose", rating: 4.4, reviewCount: 56, images: ["https://placehold.co/600x800/008080/white?text=Tropical+Shirt", "https://placehold.co/600x800/008080/gold?text=Print+Close-up"], description: "Breezy rayon shirt with a hand-designed tropical print. Vacation ready.", careInstructions: "Cold hand wash. Cool iron.", inStock: true, isTrending: true },
    { id: "v17", name: "Slim Fit Cargo Pants", brand: "M all", category: "Trousers", price: 2699, originalPrice: 3499, discountPercent: 23, sizes: ["30", "32", "34", "36"], colors: ["Olive", "Black", "Khaki"], fabric: "Cotton Ripstop", rating: 4.7, reviewCount: 112, images: ["https://placehold.co/600x800/3A5F0B/white?text=Cargo+Pants", "https://placehold.co/600x800/3A5F0B/gold?text=Pocket+Detail"], description: "Utilitarian design meets a modern slim silhouette. Crafted from durable ripstop cotton.", careInstructions: "Wash with similar colors.", inStock: true, isTrending: true },
    { id: "v18", name: "Relaxed Linen Trousers", brand: "M all", category: "Trousers", price: 2899, originalPrice: 2899, discountPercent: 0, sizes: ["30", "32", "34", "36"], colors: ["Sand", "White"], fabric: "Linen Viscose Blend", rating: 4.5, reviewCount: 64, images: ["https://placehold.co/600x800/E3DAC9/0A1628?text=Linen+Trousers", "https://placehold.co/600x800/E3DAC9/gold?text=Drawstring+Detail"], description: "Loose, comfortable fit with a drawstring waist. The ultimate summer trouser.", careInstructions: "Gentle machine wash.", inStock: true, isTrending: false },
    { id: "v19", name: "Urban Tech Joggers", brand: "M all", category: "Trousers", price: 1999, originalPrice: 2599, discountPercent: 23, sizes: ["S", "M", "L", "XL"], colors: ["Black", "Charcoal"], fabric: "Water-Resistant Nylon", rating: 4.8, reviewCount: 156, images: ["https://placehold.co/600x800/111111/white?text=Tech+Joggers", "https://placehold.co/600x800/111111/gold?text=Cuff+Detail"], description: "Modern techwear aesthetic with water-resistant fabric and ergonomic seaming.", careInstructions: "Machine wash cold. Do not iron.", inStock: true, isTrending: true },
    { id: "v20", name: "Vintage Corduroy Trousers", brand: "M all", category: "Trousers", price: 2499, originalPrice: 3800, discountPercent: 34, sizes: ["30", "32", "34", "36"], colors: ["Tan", "Burgundy"], fabric: "8-Wale Cotton Corduroy", rating: 4.6, reviewCount: 42, images: ["https://placehold.co/600x800/8B4513/white?text=Cord+Trousers", "https://placehold.co/600x800/8B4513/gold?text=Texture+Detail"], description: "Classic corduroy with a rich texture and a slightly tapered modern fit.", careInstructions: "Wash inside out to protect pile.", inStock: true, isTrending: false },
    { id: "v21", name: "Classic Harrington Jacket", brand: "M all", category: "Jackets", price: 3999, originalPrice: 4999, discountPercent: 20, sizes: ["M", "L", "XL"], colors: ["Navy", "Beige"], fabric: "Cotton Gabardine", rating: 4.9, reviewCount: 38, images: ["https://placehold.co/600x800/0A1628/white?text=Harrington+Jacket", "https://placehold.co/600x800/0A1628/gold?text=Lining+Detail"], description: "The timeless transitional jacket featuring the iconic Fraser tartan lining.", careInstructions: "Dry clean only.", inStock: true, isTrending: true },
    { id: "v22", name: "Tech Bomber Jacket", brand: "M all", category: "Jackets", price: 4499, originalPrice: 4499, discountPercent: 0, sizes: ["S", "M", "L", "XL"], colors: ["Sage", "Black"], fabric: "Flight Grade Nylon", rating: 4.7, reviewCount: 82, images: ["https://placehold.co/600x800/4B5320/white?text=Bomber+Jacket", "https://placehold.co/600x800/4B5320/gold?text=Zipper+Detail"], description: "Modern take on the MA-1 flight jacket with a slim fit and utility arm pocket.", careInstructions: "Machine wash on delicate.", inStock: true, isTrending: false },
    { id: "v23", name: "Double-Breasted Overcoat", brand: "M all", category: "Jackets", price: 8999, originalPrice: 12000, discountPercent: 25, sizes: ["38", "40", "42", "44"], colors: ["Camel", "Navy"], fabric: "Wool Cashmere Blend", rating: 5.0, reviewCount: 15, images: ["https://placehold.co/600x800/C19A6B/white?text=Overcoat", "https://placehold.co/600x800/C19A6B/0A1628?text=Lapel+Detail"], description: "The peak of winter luxury. Tailored for a commanding presence.", careInstructions: "Professional dry clean only.", inStock: true, isTrending: true },
    { id: "v24", name: "Distressed Denim Trucker", brand: "M all", category: "Jackets", price: 3299, originalPrice: 3999, discountPercent: 17, sizes: ["S", "M", "L", "XL"], colors: ["Light Blue"], fabric: "Rigid Selvedge Denim", rating: 4.6, reviewCount: 124, images: ["https://placehold.co/600x800/ADD8E6/white?text=Denim+Trucker", "https://placehold.co/600x800/ADD8E6/gold?text=Wash+Detail"], description: "Classic Type III trucker jacket with authentic distancing and metallic hardware.", careInstructions: "Cold wash only. Hang dry.", inStock: true, isTrending: false },
    { id: "v25", name: "Three-Piece Midnight Suit", brand: "M all", category: "Formals", price: 14999, originalPrice: 18999, discountPercent: 21, sizes: ["38R", "40R", "42R"], colors: ["Midnight Navy"], fabric: "Super 120s Wool", rating: 4.9, reviewCount: 22, images: ["https://placehold.co/600x800/0A1628/white?text=3-Piece+Suit", "https://placehold.co/600x800/0A1628/gold?text=Waistcoat+Detail"], description: "Exquisite three-piece suit including jacket, trousers, and matching waistcoat.", careInstructions: "Professional dry clean only.", inStock: true, isTrending: true },
    { id: "v26", name: "Silk Pocket Square Pair", brand: "M all", category: "Formals", price: 799, originalPrice: 999, discountPercent: 20, sizes: ["One Size"], colors: ["Gold/Navy", "White/Silver"], fabric: "100% Habotai Silk", rating: 4.8, reviewCount: 45, images: ["https://placehold.co/600x800/C9A84C/white?text=Pocket+Squares", "https://placehold.co/600x800/C9A84C/navy?text=Fabric+Texture"], description: "Add a final flourish to your tailoring with these hand-rolled silk pocket squares.", careInstructions: "Dry clean only.", inStock: true, isTrending: false },
    { id: "v27", name: "Wing-Collar Tuxedo Shirt", brand: "M all", category: "Formals", price: 2899, originalPrice: 3499, discountPercent: 17, sizes: ["S", "M", "L", "XL"], colors: ["White"], fabric: "Egyptian Giza Cotton", rating: 4.7, reviewCount: 18, images: ["https://placehold.co/600x800/FFFFFF/navy?text=Tuxedo+Shirt", "https://placehold.co/600x800/FFFFFF/gold?text=Bib+Detail"], description: "Formal wing-collar shirt featuring a pleated bib and French cuffs.", careInstructions: "Professional launder and press.", inStock: true, isTrending: false },
    { id: "v28", name: "Gunmetal Cufflinks Set", brand: "M all", category: "Formals", price: 1899, originalPrice: 2499, discountPercent: 24, sizes: ["30", "32", "34", "36"], colors: ["Gunmetal", "Silver"], fabric: "Polished Stainless Steel", rating: 4.8, reviewCount: 31, images: ["https://placehold.co/600x800/2D2D2D/white?text=Cufflinks", "https://placehold.co/600x800/2D2D2D/gold?text=Engraving+Detail"], description: "Minimalist geometric cufflinks for the modern executive.", careInstructions: "Wipe with soft cloth.", inStock: true, isTrending: false },
    { id: "v29", name: "Oversized Boxy Hoodie", brand: "M all", category: "Casuals", price: 2499, originalPrice: 2499, discountPercent: 0, sizes: ["S", "M", "L", "XL"], colors: ["Heather Grey", "Black", "Brown"], fabric: "Heavyweight Loopback Cotton", rating: 4.9, reviewCount: 214, images: ["https://placehold.co/600x800/808080/white?text=Boxy+Hoodie", "https://placehold.co/600x800/808080/gold?text=Fit+View"], description: "Relaxed, boxy fit hoodie with a heavy drape for the ultimate streetwear look.", careInstructions: "Wash inside out. Do not tumble dry.", inStock: true, isTrending: true },
    { id: "v30", name: "Premium Slub Graphic Tee", brand: "M all", category: "Casuals", price: 1199, originalPrice: 1599, discountPercent: 25, sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Vintage White", "Faded Black"], fabric: "Slub Cotton", rating: 4.7, reviewCount: 56, images: ["https://placehold.co/600x800/F5F5F0/0A1628?text=Graphic+Tee", "https://placehold.co/600x800/F5F5F0/gold?text=Print+Detail"], description: "Distressed logo print on a high-texture slub cotton base.", careInstructions: "Machine wash cold.", inStock: true, isTrending: false },
    { id: "v31", name: "Classic Pique Polo", brand: "M all", category: "Casuals", price: 1599, originalPrice: 1999, discountPercent: 20, sizes: ["M", "L", "XL"], colors: ["Navy", "White", "Burgundy"], fabric: "Honeycomb Pique Cotton", rating: 4.6, reviewCount: 142, images: ["https://placehold.co/600x800/0A1628/white?text=Pique+Polo", "https://placehold.co/600x800/0A1628/gold?text=Logo+Detail"], description: "The essential smart-casual polo. Durable, breathable, and timeless.", careInstructions: "Avoid using fabric softeners.", inStock: true, isTrending: false },
    { id: "v32", name: "Minimalist Canvas Sneakers", brand: "M all", category: "Casuals", price: 2299, originalPrice: 2299, discountPercent: 0, sizes: ["7", "8", "9", "10", "11"], colors: ["Off-White", "Navy"], fabric: "12oz Organic Canvas", rating: 4.5, reviewCount: 89, images: ["https://placehold.co/600x800/F5F5F0/0A1628?text=Sneakers", "https://placehold.co/600x800/F5F5F0/gold?text=Sole+Detail"], description: "Clean silhouettes and premium canvas. Built for daily comfort.", careInstructions: "Spot clean with mild soap.", inStock: true, isTrending: true },
    { id: "v33", name: "Chronograph Steel Watch", brand: "M all", category: "Accessories", price: 7499, originalPrice: 9999, discountPercent: 25, sizes: ["One Size"], colors: ["Silver/Navy", "Gold/Black"], fabric: "Stainless Steel / Sapphire Glass", rating: 4.9, reviewCount: 24, images: ["https://placehold.co/600x800/2D2D2D/white?text=Steel+Watch", "https://placehold.co/600x800/2D2D2D/gold?text=Dial+Close-up"], description: "Precision timekeeping meet modern industrial design.", careInstructions: "Wipe with dry microfiber cloth.", inStock: true, isTrending: true },
    { id: "v34", name: "Bi-Fold Saffiano Wallet", brand: "M all", category: "Accessories", price: 1999, originalPrice: 2499, discountPercent: 20, sizes: ["One Size"], colors: ["Black", "Nero"], fabric: "Saffiano Grain Leather", rating: 4.8, reviewCount: 67, images: ["https://placehold.co/600x800/111111/white?text=Leather+Wallet", "https://placehold.co/600x800/111111/gold?text=Interior+Slots"], description: "Scratch-resistant saffiano leather with RFID protection.", careInstructions: "Avoid contact with water.", inStock: true, isTrending: false },
    { id: "v35", name: "Aviator Blue-Light Glasses", brand: "M all", category: "Accessories", price: 1299, originalPrice: 1899, discountPercent: 31, sizes: ["One Size"], colors: ["Gunmetal", "Gold"], fabric: "Acetate / Metal Alloy", rating: 4.7, reviewCount: 88, images: ["https://placehold.co/600x800/2D2D2D/white?text=Aviators", "https://placehold.co/600x800/2D2D2D/gold?text=Side+View"], description: "Classic aviator frames with modern blue-light filtering lenses.", careInstructions: "Wash with luke-warm water.", inStock: true, isTrending: false },
    { id: "v36", name: "Cashmere Blend Scarf", brand: "M all", category: "Accessories", price: 2299, originalPrice: 2899, discountPercent: 20, sizes: ["One Size"], colors: ["Camel", "Grey", "Navy"], fabric: "Wool Cashmere Blend", rating: 4.9, reviewCount: 42, images: ["https://placehold.co/600x800/C19A6B/white?text=Winter+Scarf", "https://placehold.co/C19A6B/gold?text=Knit+Detail"], description: "Luxuriously soft and warm. A sophisticated addition to your winter layering.", careInstructions: "Dry clean only.", inStock: true, isTrending: false }
  ];

  for (const p of products) {
    const { category, id: _tempId, ...productData } = p;
    await prisma.product.upsert({
      where: { slug: p.name.toLowerCase().replace(/ /g, '-') },
      update: {
        ...productData,
        categoryId: categoryRecords[category].id,
      },
      create: {
        ...productData,
        slug: p.name.toLowerCase().replace(/ /g, '-'),
        categoryId: categoryRecords[category].id,
      },
    });
  }

  console.log('Full Seeding complete! 36 products added.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
